### ISSUE TITLE
Read MLX30393 using Esp32

### ISSUE THREAD

**Issue by Olseda20** [FoR-Group1/OpenWhisker#15]
We want to get readings off of the MLX30393 using the ESP32 to get higher frequncy of measurement.

#### Tasks:
- [ ] Get computer to read the ESP32 
    - [ ] could be good to setup a guide from scratch? (ie perms and all)
- [ ] Correctly connect MLX30393 to computer (pins and such)
- [ ] Modified MLX30393_Adafruit library
    - [ ] to reduce delays in readings (removing oversampling and gain?) - more to explore
    - [ ] increase the frequency of the I2C clock
    - [ ] cleaned up to remove SPI functionality
- [ ] Rebuild/re-write code making use of MLX30393_Adafruit as a template 

Resources so far:
ESP32-WROOM-32 datasheet: https://espressif.com/sites/default/files/documentation/esp32-wroom-32e_esp32-wroom-32ue_datasheet_en.pdf

ML30393 datasheet: https://www.melexis.com/en/documents/documentation/application-notes/application-note-mlx90393-getting-started-guide

kiCad library for ESP32: https://github.com/espressif/kicad-libraries
